### ISSUE TITLE
What is the best way to calculate 200,000 records in C # with variadic arguments?

### ISSUE THREAD

**Issue by nwide-m-system** [mariuszgromada/MathParser.org-mXparser#248]
### Question title:
What is the best way to calculate 200,000 records in C # with variadic arguments?
Expression needs to be updated in the for statement. (argument max 9)

Another problem, I'm creating an Expression in a For statement, so a memory leak occurs in the middle of the process and it doesn't continue.
The expression needs to be changed in the For statement.

Or do I need to use any other method?

I'm not English speaking, but I wasn't sure when I translated and read the api docs.

#### Question:
- MathParser.org-mXparser version: 4.4.2
- Framework: .net6
- Code example
```C#
Argument a = new Argument("a", 0);
Argument b = new Argument("b", 0);
Argument c = new Argument("c", 0);
Argument d = new Argument("d", 0);
Argument e = new Argument("e", 0);
Argument f = new Argument("f", 0);
Argument g = new Argument("g", 0);
Argument h = new Argument("h", 0);
Argument i = new Argument("i", 0);
   
for (int k = 0; k < 200000; k++) {
    // Not all are used.
    a.setArgumentValue(1);
    b.setArgumentValue(1);
    // c.setArgumentValue(0);
    // d.setArgumentValue(0);
    // e.setArgumentValue(0);
    // f.setArgumentValue(0);
    // g.setArgumentValue(0);
    // h.setArgumentValue(0);
    // i.setArgumentValue(0);
    
    Expression expression = new Expression("a + b", a, b /*, c, d, e, f, g, h, i */);
    double result = expression.calculate();
    double value = !Double.IsNaN(result) ? result : 0;
 }
```
I think ...
However, it seems that there is still a memory leak.

```C#
for (int k = 0; k < 200000; k++) {
     string a = "1";
     string b = "1";

     // In my code, replace is a perfect match.
     string expressionString =  "a + b".Replace("a", a).Replace("b", b);    // "1 + 2"

     Expression expression = new Expression(expressionString);
     double result = expression.calculate();

     decimal value = 0;
     decimal.TryParse(result.ToString(), out value);
     
     Console.WriteLine(value);    // 3
}
```

**Comment by mariuszgromada** [comment]
Hi,

Please create Expression just once, add definitions and the just change the argument values. mXparser pre-compliles expression and does not need to do it once agian after changing expression value. do the following.


```
Argument a = new Argument("a", 0);
Argument b = new Argument("b", 0);
Argument c = new Argument("c", 0);
Argument d = new Argument("d", 0);
Argument e = new Argument("e", 0);
Argument f = new Argument("f", 0);
Argument g = new Argument("g", 0);
Argument h = new Argument("h", 0);
Argument i = new Argument("i", 0);

Expression expression = new Expression("a + b", a, b /*, c, d, e, f, g, h, i */);
  
for (int k = 0; k < 200000; k++) {
    // Not all are used.
    a.setArgumentValue(1);
    b.setArgumentValue(1);
    // c.setArgumentValue(0);
    // d.setArgumentValue(0);
    // e.setArgumentValue(0);
    // f.setArgumentValue(0);
    // g.setArgumentValue(0);
    // h.setArgumentValue(0);
    // i.setArgumentValue(0);
    
    double result = expression.calculate();
    double value = !Double.IsNaN(result) ? result : 0;
 }
```


In terms of memory leakage - mXparser maintains relationships between objects, you just created a hundred thousand objects that are related to each other. If expression `e` uses Argument `a` then `a` keeps inside relation to `e` in order to notify `e` in case of `a` changed something important (for instance its name). Simply syntax correctness of `e` depends on `a`. If expression `e` was pre-compiled, then no need to check the syntax once again after argument value changed, but there is a need to pre-comile `e` once again if something more has changed in `a`.

Take a look here
http://mathparser.org/mxparser-tutorial/user-defined-arguments/

and here
http://mathparser.org/mxparser-tutorial/inspecting-calculation-process/

and generally here
http://mathparser.org/mxparser-tutorial/

Best regards

**Comment by nwide-m-system** [comment]
Thank you for your reply.

The Argument problem is resolved. In my environment, using Argument is expensive, so I don't use it, but use "replace" of ".NET".

The problem I'm having right now is changing the expression inside a for loop. However, a memory leak will occur.

Does mXparser not support changing expressions inside for loops?

-
// I want to do now
Expression expression = new Expression ("");

for (int k = 0; k <200000; k ++) {
    string a = "1";
    string b = "1";

    // In my environment, using Argument is expensive, so I don't use it, but use "replace" of ".NET".
    string newExpresssionString = "a + b";
    string expresssionString = newExpresssionString.Replace ("a", a) .Replace ("b", b); // "1 + 2"

    // I want to change the expression in for
    expression.setExpressionString (expressionString);

    double result = expression.calculate ();
    double value =! Double.IsNaN (result)? result: 0;

    // GC.Collect has no effect
    GC.Collect ();
}
-

**Comment by mariuszgromada** [comment]
If constructor / string change inside a loop, you create always new string
expression, then on calculat() all grammar / lexical analysis has to be
performed - this grammar analysis is a heavy task.

To support loop case Argument class was created. Define expression once,
add argument, then in a loop change argument value and call calculate. It
will be very fast.

I do not believe that many calls to string replace plus calculate will be
faster than argument set value and calculate.

Best regards

czw., 10 lut 2022, 01:16 użytkownik nwide-m-system ***@***.***>
napisał:

**Comment by nwide-m-system** [comment]
Thank you. I understand.

I set the Argument outside the loop and changed its value inside the loop.

The processing speed up to this point seems to be the limit.
(It may be affected by the specifications of the server machine.)

10000 row: 17 second.
20000 row: 540 second.

It is solved. Thank you.

```C#
IList<Expression> expressionLists = new List<Expression>();

Argument a = new Argument("a", 0);
Argument b = new Argument("b", 0);
Argument c = new Argument("c", 0);
Argument d = new Argument("d", 0);
Argument e = new Argument("e", 0);
Argument f = new Argument("f", 0);
Argument g = new Argument("g", 0);
Argument h = new Argument("h", 0);
Argument i = new Argument("i", 0);

for (int k = 0; k < 1000; k++) {
    string functionName = "at(a+b)";
    string expressionString = "a+b";
    Function function = new Function(functionName + " = " + expressionString);
    Expression expression = new Expression(functionName, function, a, b);

    expressionLists.Add(expression);
}

 for (int k = 0; k < 200000; k++) {
     // test key 0
     Expression expression = expressionLists[0];                    
     a.setArgumentValue(1);
     b.setArgumentValue(1);
     c.setArgumentValue(1);
     d.setArgumentValue(1);
     e.setArgumentValue(1);
     f.setArgumentValue(1);
     g.setArgumentValue(1);
     h.setArgumentValue(1);
     i.setArgumentValue(1);

     double result = expression.calculate();
     double value = !Double.IsNaN(result) ? result : 0;

     expression.removeAllArguments();
}
```

**Comment by mariuszgromada** [comment]
Hi,
I still see you can improove your code performance really strongly. Ate the end of a loop you have `expression.removeAllArguments();` - this will trigger syntax checking in each iteration ...  Why? It is simple - If you remove argument you may destroy expression structure.

Try below code and let me know the performance boost

```C#
Expression expression = expressionLists[0];                    

for (int k = 0; k < 200000; k++) {
     // test key 0
     a.setArgumentValue(1);
     b.setArgumentValue(1);
     c.setArgumentValue(1);
     d.setArgumentValue(1);
     e.setArgumentValue(1);
     f.setArgumentValue(1);
     g.setArgumentValue(1);
     h.setArgumentValue(1);
     i.setArgumentValue(1);

     double result = expression.calculate();
     double value = !Double.IsNaN(result) ? result : 0;
}

expression.removeAllArguments();
```
